services:
  application:
    build:
      context: ./application
      dockerfile: Dockerfile
    container_name: application
    network_mode: host
    volumes:
      - ./application/build/libs:/app/libs
    environment:
      - JAVA_OPTS=-Djava.security.egd=file:/dev/./urandom

  softphone:
    build:
      context: ./softphone
      dockerfile: Dockerfile
    container_name: softphone
    network_mode: host
    volumes:
      - ./softphone:/app
      - softphone_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

volumes:
  softphone_node_modules: